version: '3.3'

services:
  elb:
    ports:
      - '80:8080'
      - '443:8443'
      - '9443:9443'
  app:
    ports:
      - '4200:4200'
  backend:
    ports:
      - '8080:8080'
  database:
    ports:
      - '5432:5432'
  redis:
    ports:
      - '6379:6379'
