version: '3.3'
services:
  elb:
    build:
      context: 'apps/elb'
      args:
        ENABLED_MODULES: brotli
  app:
    build:
      dockerfile: 'apps/app/Dockerfile'
      args:
        - GIT_VERSION
        - GIT_COMMIT
  backend:
    build:
      dockerfile: 'apps/backend/Dockerfile'
      args:
        - GIT_VERSION
        - GIT_COMMIT
  agent:
    build:
      dockerfile: 'apps/agent/Dockerfile'
      args:
        - GIT_VERSION
        - GIT_COMMIT
  database:
    image: postgres:14.6
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: reachout
      POSTGRES_USER: reachout
      POSTGRES_PASSWORD: reachout
    ports:
      - "5432:5432"
    volumes:
      - ./local/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0.5-alpine3.16
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    volumes:
      - ./apps/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
