# Base Image
FROM node:18.16.0-alpine3.18 AS deps
WORKDIR /app

# Set timezone and install system dependencies
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apk add --no-cache make gcc g++ python3 git

# Copy configs and install dependencies
COPY package.json tsconfig.json tsconfig.base.json .env jest.config.ts jest.preset.js .npmrc nx.json env.mjs yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
RUN yarn install --frozen-lockfile

# Copy source files
COPY . .

# Expose ports
EXPOSE 8080 8040 9229

CMD ["sh", "-c", "yarn migration:run && yarn start backend"]
