FROM node:18.16.0-alpine3.18

# set timezone
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apk add --no-cache make gcc g++ python3 git

WORKDIR /app
ENV NODE_ENV=development

# install dependencies
COPY package.json tsconfig.json tsconfig.base.json .env .env.example package-lock.json yarn.lock jest.config.ts jest.preset.js .npmrc .yarnrc nx.json .env env.mjs ./
RUN yarn global add nx@14.8.6
RUN yarn install --check-files --frozen-lockfile && yarn cache clean

# copy source files
COPY libs/  ./libs/
COPY scripts/  ./scripts/
COPY apps/ ./apps/

# change user
# RUN adduser -D worker
# USER worker

# expose ports
EXPOSE 8080
EXPOSE 8040
EXPOSE 9229

CMD yarn migration:run && yarn start backend
